---
title: "strings_and_factors"
author: "Ruihan Ding"
date: "2025-10-21"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(p8105.datasets)
```

## Mostly use string vectors

```{r}
string_vec = c("my", "name", "is", "Arwen")

str_detect(string_vec, "Arwen")
str_detect(string_vec, "e")

str_replace(string_vec, "Arwen", "")
str_remove(string_vec, "e")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think")  # ^ means start of the string
str_detect(string_vec, "i think$")  # $ means end of the string

str_remove(string_vec, "i think$")
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Pp]umpkin")
```

Let's get a bit more complicated

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7\\.1")
# . means anything (this is a special character),
# \ means the thing after is not a special character, need \\
```

## Factors

```{r}
vec_sex = factor(c("male", "male", "female", "female"))

vec_sex = fct_inorder(vec_sex)
```

## Revisit NSDUH

```{r}
url = "https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use = read_html(url)
nsduh_df = 
  drug_use |> 
  html_table() |> 
  first() |>
  slice(-1)
```

Now do the tidying

```{r}
marj_df =
  nsduh_df |> 
  select(-contains("P value")) |> 
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent"
  ) |> 
  separate(age_year, into = c("age", "year"), sep = "\\(") |> 
  mutate(
    year = str_remove(year, "\\)"),
    percent = str_remove(percent, "[a-c]$"),
    percent = as.numeric(percent)
  ) |> 
  filter(
    !(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West"))
  )
# when filtering for items in a collection, use %in%
```

Let's make a plot

```{r}
marj_df |> 
  filter(age == "12-17") |> 
  mutate(State = fct_reorder(State, percent)) |> 
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## Restaurant Inspections

```{r}
data("rest_inspec")
```

```{r}
rest_inspec |> 
  group_by(boro, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(
    names_from = grade,
    values_from = n
  )
```

uodate the dataset

```{r}
rest_inspec = 
  rest_inspec |> 
  filter(grade %in% c("A", "B", "C"),
         boro != 0)
```

Look for pizza places

```{r}
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |> 
  group_by(boro, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(
    names_from = grade,
    values_from = n
  )
```

Let's make a plot

```{r}
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |> 
  mutate(
    boro = fct_infreq(boro),
    boro = str_replace(boro, "Manhattan", "The City")) |>  
    # converted it back to string
  ggplot(aes(x = boro, fill = grade)) +
  geom_bar()
```

The previous one doesn't work as intended, but the below one does.

```{r}
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |> 
  mutate(
    boro = fct_infreq(boro),
    boro = fct_recode(boro, "The City" = "Manhattan")) |>  
  ggplot(aes(x = boro, fill = grade)) +
  geom_bar()
```







